controller_manager:
  ros__parameters:
    update_rate: 30
    use_sim_time: true

    diff_cont:
      type: diff_drive_controller/DiffDriveController

    joint_state_broadcaster:
      type: joint_state_controller/JointStateBroadcaster

diff_cont:
  ros__parameters:
    
    publish_rate: 50.0

    base_frame: base_link

    left_wheel_names: ['fl_wheel_joint']
    right_wheel_names: ['fr_wheel_joint']
    wheel_separation: 0.35
    wheel_radius: 0.05

    use_stamped_vel: false