controller_manager:
  ros__parameters:
    update_rate: 30

    diffdrive_controller:
      type: diff_drive_controller/DiffDriveController

    joint_state_broadcaster:
      type: joint_state_broadcaster/JointStateBroadcaster

diffdrive_controller:
  ros__parameters:
    
    publish_rate: 50.0
    use_sim_time: True

    base_frame: base_link

    left_wheel_names: ['fl_wheel_joint']
    right_wheel_names: ['fr_wheel_joint']
    wheel_separation: 0.35
    wheel_radius: 0.05

    use_stamped_vel: false