controller_manager:
  ros__parameters:
    update_rate: 30

    ackermannSteering_controller:
      type: ackermann_steering_controller/AckermannSteeringController

    joint_state_broadcaster:
      type: joint_state_broadcaster/JointStateBroadcaster

diffdrive_controller:
  ros__parameters:
    
    publish_rate: 50.0
    use_sim_time: True

    base_frame_id: base_footprint

    front_steering: true
    open_loop: false
    velocity_rolling_window_size: 10
    position_feedback: false

    front_wheels_names: ['fl_wheel_joint', 'fr_wheel_joint']
    rear_wheels_names: ['ml_wheel_joint', 'mr_wheel_joint']

    wheelbase: 0.40
    front_wheel_track: 0.38
    rear_wheel_track: 0.38
    front_wheels_radius: 0.075
    rear_wheels_radius: 0.075

    