controller_manager:
  ros__parameters:
    update_rate: 100

    joint_state_broadcaster:
      type: joint_state_broadcaster/JointStateBroadcaster

    rover_controller:
      type: rover_controller/RoverController

rover_controller:
  ros__parameters:
    drive_joint_names: ["front_left_wheel_joint", "front_right_wheel_joint", "mid_left_wheel_joint", "mid_right_wheel_joint", "rear_left_wheel_joint", "rear_right_wheel_joint"]
    steering_joint_names: ["front_left_servo_joint", "front_right_servo_joint", "rear_left_servo_joint", "rear_right_servo_joint"]

    odom_frame_id: "odom"
    base_frame_id:  "base_footprint"

    wheel_radius: .075
    track_width: 0.38
    wheelbase: 0.40

    enable_odom_tf: false
    use_sim_time: false
    pose_covariance_diagonal: [0.0, 0.0, 0.0, 0.0, 0.0, 0.0]
    twist_covariance_diagonal: [0.0, 0.0, 0.0, 0.0, 0.0, 0.0]

    cmd_vel_timeout: 1000

    vel_limit: 10.0
    angle_limit: 0.785