<?xml version='1.0'?>
<robot xmlns:xacro='http://www.ros.org/wiki/xacro'>

    <!--Arm Link-->
    <xacro:macro name='arm_link' params='name parent_link arm_length mesh *origin *limit *inertial'>

        <xacro:property name='arm_link_name' value='${name}'/>
        <xacro:property name='arm_joint_name' value='${name}_joint'/>

        <joint name='${arm_joint_name}' type='revolute'>
            <parent link='${parent_link}'/>
            <child link='${arm_link_name}'/>
            <xacro:insert_block name='origin'/>
            <xacro:insert_block name='limit'/>
            <axis xyz='0 1 0'/>
        </joint>

        <link name='${arm_link_name}'>
            <visual>
                <origin xyz='${-arm_length/2} 0 0' rpy='0 ${pi/2} 0'/>
                <geometry>
                    <cylinder length='${arm_length}' radius='${arm_radius}'/>
                </geometry>
                <xacro:insert_block name='material_orange'/>
            </visual>
            <collision>
                <origin xyz='${-arm_length/2} 0 0' rpy ='0 ${pi/2} 0'/>
                <geometry>
                    <cylinder length='${arm_length}' radius='${arm_radius}'/>
                </geometry>
            </collision>
            <xacro:inertial_cylinder_with_pose mass='${arm_mass}' length='${arm_length}' radius='${arm_radius}'>
                <origin xyz='${-arm_length/2} 0 0' rpy='0 ${pi/2} 0'/>
            </xacro:inertial_cylinder_with_pose>
        </link>
    </xacro:macro> 

    <!--Arm Link Mimic-->
    <xacro:macro name='arm_link_mimic' params='name parent_link arm_length mesh *origin *limit *inertial *mimic'>

        <xacro:property name='arm_link_name' value='${name}'/>
        <xacro:property name='arm_joint_name' value='${name}_joint'/>

        <joint name='${arm_joint_name}' type='revolute'>
            <parent link='${parent_link}'/>
            <child link='${arm_link_name}'/>
            <xacro:insert_block name='origin'/>
            <xacro:insert_block name='limit'/>
            <xacro:insert_block name='mimic'/>
            <axis xyz='0 1 0'/>
        </joint>

        <link name='${arm_link_name}'>
            <visual>
                <origin xyz='${-arm_length/2} 0 0' rpy='0 ${pi/2} 0'/>
                <geometry>
                    <cylinder length='${arm_length}' radius='${arm_radius}'/>
                </geometry>
                <xacro:insert_block name='material_orange'/>
            </visual>
            <collision>
                <origin xyz='${-arm_length/2} 0 0' rpy ='0 ${pi/2} 0'/>
                <geometry>
                    <cylinder length='${arm_length}' radius='${arm_radius}'/>
                </geometry>
            </collision>
            <xacro:inertial_cylinder_with_pose mass='${arm_mass}' length='${arm_length}' radius='${arm_radius}'>
                <origin xyz='${-arm_length/2} 0 0' rpy='0 ${pi/2} 0'/>
            </xacro:inertial_cylinder_with_pose>
        </link>
    </xacro:macro> 

</robot>