<?xml version='1.0'?>
<robot xmlns:xacro='http://www.ros.org/wiki/xacro' name='rushbott'>

    <xacro:include filename='common_properties.urdf.xacro'/>
    <xacro:include filename='wheel.urdf.xacro'/>
    <xacro:include filename='wheel_with_servo.urdf.xacro'/>
    <xacro:include filename='arm_link.urdf.xacro'/>

    <!-- Mechanical properties -->
    <xacro:property name='body_mass'               value='2.300' />
    <xacro:property name='body_length'             value='${50*cm2m}' />
    <xacro:property name='body_width'              value='${30*cm2m}' />
    <xacro:property name='body_height'             value='${20*cm2m}' />

    <xacro:property name='wheel_mass'              value='0.2' />
    <xacro:property name='wheel_radius'            value='${7.5*cm2m}' />
    <xacro:property name='wheel_width'             value='${5*cm2m}' />
    <xacro:property name='wheel_depth'             value='${wheel_radius}' />
    <xacro:property name='wheelbase'               value='${40*cm2m}' />
    <xacro:property name='track_width'             value='${38*cm2m}' />

    <xacro:property name='servo_mass'              value='0.2' />
    <xacro:property name='servo_radius'            value='${3*cm2m}' />
    <xacro:property name='servo_width'             value='${4*cm2m}' />
    <xacro:property name='servo_height'            value='${wheel_radius+3*cm2m}' />

    <xacro:property name='lower_arm_length'        value='${50*cm2m}'/>
    <xacro:property name='lower_arm_mass'          value='0.05'/>
    <xacro:property name='upper_control_length'    value='${20*cm2m}'/>
    <xacro:property name='upper_control_mass'      value='0.05'/>
    <xacro:property name='upper_link_length'       value='${lower_arm_length}'/>
    <xacro:property name='upper_link_mass'         value='0.05'/>
    <xacro:property name='upper_arm_length'        value='${100*cm2m}'/>
    <xacro:property name='upper_arm_mass'          value='0.05'/>
    <xacro:property name='suction_head_length'     value='${5*cm2m}'/>
    <xacro:property name='suction_head_mass'       value='0.05'/>
    <xacro:property name='arm_radius'              value='${2*cm2m}'/>
    <xacro:property name='arm_x_position'          value='${2*cm2m}'/>
    <xacro:property name='arm_y_position'          value='${2*cm2m}'/>


    <!-- Base footprint --> 
    <link name='base_footprint'/>

    <!-- Base link --> 
    <joint name='base_footprint_to_base_link' type='fixed'>  
        <parent link='base_footprint'/>  
        <child link='base_link'/>  
        <origin xyz='0 0 ${wheel_depth+wheel_radius}'/>
    </joint>

    <link name='base_link'>
        <visual>
            <origin xyz='0 0 ${body_height/2}'/>
            <geometry>
                <box size='${body_length} ${body_width} ${body_height}'/>
            </geometry>
            <xacro:insert_block name='material_cyan'/>
        </visual>
        <collision>
            <origin xyz='0 0 ${body_height/2}'/>
            <geometry>
                <box size='${body_length} ${body_width} ${body_height}'/>
            </geometry>
        </collision>
        <xacro:inertial_cuboid_with_pose mass='${body_mass}' x='${body_length}' y='${body_width}' z='${body_height}'>
            <origin xyz='0 0 ${body_height/2}'/>
        </xacro:inertial_cuboid_with_pose>
    </link>

    <!-- Wheels with servos--> 
    <xacro:wheel_with_servo name='front_left' parent_link='base_link'>
        <origin xyz='${wheelbase/2} ${track_width/2} ${-wheel_depth+servo_height}' rpy='0 0 0'/>
        <axis xyz='0 0 1'/>
    </xacro:wheel_with_servo>

    <xacro:wheel_with_servo name='front_right' parent_link='base_link'>
        <origin xyz='${wheelbase/2} ${-track_width/2} ${-wheel_depth+servo_height}' rpy='0 0 ${pi}'/>
        <axis xyz='0 0 -1'/>
    </xacro:wheel_with_servo>

    <xacro:wheel_with_servo name='rear_left' parent_link='base_link'>
        <origin xyz='${-wheelbase/2} ${track_width/2} ${-wheel_depth+servo_height}' rpy='0 0 0'/>
        <axis xyz='0 0 1'/>
    </xacro:wheel_with_servo>

    <xacro:wheel_with_servo name='rear_right' parent_link='base_link'>
        <origin xyz='${-wheelbase/2} ${-track_width/2} ${-wheel_depth+servo_height}' rpy='0 0 ${pi}'/>
        <axis xyz='0 0 -1'/>
    </xacro:wheel_with_servo>
    
    <!-- Wheels--> 
    <xacro:wheel name='mid_left' parent_link='base_link'>
        <origin xyz='0 ${track_width/2} ${-wheel_depth}' rpy='${-pi/2} 0 0'/>
        <axis xyz='0 0 1'/>
    </xacro:wheel>

    <xacro:wheel name='mid_right' parent_link='base_link'>
        <origin xyz='0 ${-track_width/2} ${-wheel_depth}' rpy='${-pi/2} 0 ${pi}'/>
        <axis xyz='0 0 -1'/>
    </xacro:wheel>

    <!-- Gazebo (make this conditional later on)-->
    <gazebo>
        <plugin filename='libgz_ros2_control-system.so' name='gz_ros2_control::GazeboSimROS2ControlPlugin'>
            <parameters>$(find rushbott_control)/config/control.yaml</parameters>
        </plugin>
    </gazebo>

    <!-- Arm --> 
    <xacro:arm_link name='lower_arm' parent_link='base_link' arm_length='${lower_arm_length}' arm_mass='${lower_arm_mass}'>
        <origin xyz='0 0 0.3' rpy='0 0 0'/>
        <limit lower='0' upper='${pi}' effort='10' velocity='10'/>
    </xacro:arm_link>

    <xacro:arm_link name='upper_control' parent_link='lower_arm' arm_length='${upper_control_length}' arm_mass='${upper_control_mass}'>
        <origin xyz='0 0 0' rpy='0 0 0'/>
        <limit lower='${-pi/2}' upper='${pi/2}' effort='10' velocity='10'/>
    </xacro:arm_link>

    <xacro:arm_link_mimic name='upper_link' parent_link='upper_control' arm_length='${lower_arm_length}' arm_mass='${upper_link_mass}'>
        <origin xyz='${-upper_control_length} 0 0' rpy='0 0 0'/>
        <limit lower='${-pi/2}' upper='${pi/2}' effort='10' velocity='10'/>
        <mimic joint='upper_control_joint' multiplier='-1.0'/>
    </xacro:arm_link_mimic>

    <xacro:arm_link_mimic name='upper_arm' parent_link='upper_link' arm_length='${lower_arm_length}' arm_mass='${upper_arm_mass}'>
        <origin xyz='${-upper_link_length} 0 0' rpy='0 0 0'/>
        <limit lower='${-pi/2}' upper='${pi/2}' effort='10' velocity='10'/>
        <mimic joint='upper_control_joint' multiplier='1.0' offset='${pi}'/>
    </xacro:arm_link_mimic>

    <!-- <xacro:arm_link name='suction_head' parent_link='upper_arm' arm_length='${suction_head_length}' arm_mass='${suction_head_mass}'>
        <origin xyz='${upper_arm_length} 0 0' rpy='0 0 0'/>
        <limit lower='${-pi/2}' upper='${pi/2}' effort='10' velocity='10'/>
    </xacro:arm_link> -->

</robot>