<?xml version='1.0'?>
<robot xmlns:xacro='http://www.ros.org/wiki/xacro' name='rushbott'>

    <xacro:include filename='common_properties.urdf.xacro'/>
    <xacro:include filename='wheel.urdf.xacro'/>
    <xacro:include filename='wheel_with_servo.urdf.xacro'/>
    <xacro:include filename="arm.urdf.xacro"/>
    <xacro:include filename="upperarm.urdf.xacro"/>
    <xacro:include filename="lidar.urdf.xacro"/>

    <!-- Mechanical properties -->
    <xacro:property name='body_mass'               value='2.300' />
    <xacro:property name='body_length'             value='${50*cm2m}' />
    <xacro:property name='body_width'              value='${30*cm2m}' />
    <xacro:property name='body_height'             value='${20*cm2m}' />

    <xacro:property name='wheel_mass'              value='0.2' />
    <xacro:property name='wheel_radius'            value='${7.5*cm2m}' />
    <xacro:property name='wheel_width'             value='${5*cm2m}' />
    <xacro:property name='wheel_depth'             value='${wheel_radius}' />
    <xacro:property name='wheelbase'               value='${40*cm2m}' />
    <xacro:property name='track_width'             value='${38*cm2m}' />

    <xacro:property name='servo_mass'              value='0.2' />
    <xacro:property name='servo_radius'            value='${3*cm2m}' />
    <xacro:property name='servo_width'             value='${4*cm2m}' />
    <xacro:property name='servo_depth'            value='${wheel_radius+3*cm2m}' />

    <xacro:property name = "arm_length" value = "1"/>
    <xacro:property name = "arm_radius" value = "0.05"/>

    <!-- Base footprint --> 
    <link name='base_footprint'/>

    <!-- Base link --> 
    <joint name="base_footprint_to_base_link" type="fixed">  
        <parent link="base_footprint"/>  
        <child link="base_link"/>  
    </joint>

    <link name='base_link'>
        <visual>
            <origin xyz='0 0 ${body_height/2}'/>
            <geometry>
                <box size='${body_length} ${body_width} ${body_height}'/>
            </geometry>
            <xacro:insert_block name='material_cyan'/>
        </visual>
        <collision>
            <origin xyz='0 0 ${body_height/2}'/>
            <geometry>
                <box size='${body_length} ${body_width} ${body_height}'/>
            </geometry>
        </collision>
        <xacro:inertial_cuboid_with_pose mass='${body_mass}' x='${body_length}' y='${body_width}' z='${body_height}'>
            <origin xyz='0 0 ${body_height/2}'/>
        </xacro:inertial_cuboid_with_pose>
    </link>

    <!-- Wheels with servos--> 

    <xacro:wheel_with_servo name='fl' parent_link='base_link'>
        <origin xyz='${wheelbase/2} ${track_width/2} ${-wheel_depth+servo_depth}' rpy='0 0 0'/>
        <axis xyz='0 0 1'/>
    </xacro:wheel_with_servo>

    <xacro:wheel_with_servo name='fr' parent_link='base_link'>
        <origin xyz='${wheelbase/2} ${-track_width/2} ${-wheel_depth+servo_depth}' rpy='0 0 ${pi}'/>
        <axis xyz='0 0 -1'/>
    </xacro:wheel_with_servo>

    <xacro:wheel_with_servo name='rl' parent_link='base_link'>
        <origin xyz='${-wheelbase/2} ${track_width/2} ${-wheel_depth+servo_depth}' rpy='0 0 0'/>
        <axis xyz='0 0 1'/>
    </xacro:wheel_with_servo>

    <xacro:wheel_with_servo name='rr' parent_link='base_link'>
        <origin xyz='${-wheelbase/2} ${-track_width/2} ${-wheel_depth+servo_depth}' rpy='0 0 ${pi}'/>
        <axis xyz='0 0 -1'/>
    </xacro:wheel_with_servo>
    
    <!-- Wheels--> 

    <xacro:wheel name='l' parent_link='base_link'>
        <origin xyz='0 ${track_width/2} ${-wheel_depth}' rpy='${-pi/2} 0 0'/>
        <axis xyz='0 0 1'/>
    </xacro:wheel>

    <xacro:wheel name='r' parent_link='base_link'>
        <origin xyz='0 ${-track_width/2} ${-wheel_depth}' rpy='${-pi/2} 0 ${pi}'/>
        <axis xyz='0 0 -1'/>
    </xacro:wheel>

    <!-- Gazebo (make this conditional later on)-->
    <gazebo>
        <plugin filename="libgz_ros2_control-system.so" name="gz_ros2_control::GazeboSimROS2ControlPlugin">
            <parameters>$(find rushbott_control)/config/control.yaml</parameters>
        </plugin>
    </gazebo>
    
    <!-- Lower Arm -->
    <xacro:arm name = "lower_arm" parent_link = "base_link">
        <origin xyz = "0 0 0" rpy = "0 0 0"/>
        <limit lower = "0" upper = "${pi/2}" velocity = "100" effort = "100"/>
    </xacro:arm>

    <!-- Upper Arm -->
    <xacro:upperarm name = "upper_arm" parent_link = "lower_arm_link">
        <origin xyz = "${arm_length} 0 0" rpy = "0 0 0"/>
    </xacro:upperarm>

    <!-- Lidar -->
    <xacro:lidar name="lidar" parent_link="base_footprint">
        <origin xyz="0.122 0 ${body_height}" rpy="0 0 0"/>
    </xacro:lidar>

</robot>